import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Box} from "@mui/system";
import React from "react";
import {AppBar, IconButton, Toolbar, Typography} from "@mui/material";
import {AppRouterCacheProvider} from "@mui/material-nextjs/v13-appRouter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <AppRouterCacheProvider>
      <Box sx={{ flexGrow: 1 }} >
          <AppBar sx={{backgroundColor: "#0A1F32", color:"#D2D2D2"}} position="static">
              <Toolbar>
                  <Typography
                      variant="h5"
                      noWrap
                      component="div"
                      color="inherit"
                      sx={{ flexGrow: 1, display: { xs: 'none', sm: 'block' } }}
                  >
                      Stock quotes
                  </Typography>

                  <Typography
                      variant="h6"
                      noWrap
                      component="div"
                      color="inherit"
                      sx={{ flexGrow: 1, display: { xs: 'none', sm: 'block' } }}
                  >
                     Sma period for charts {process.env.NEXT_PUBLIC_SMA_PERIOD_MINUTES} min.
                  </Typography>

              </Toolbar>
          </AppBar>
      </Box>
          <Box sx={{width: "95%", margin: " 20px auto"}}>
              {children}
          </Box>
      </AppRouterCacheProvider>
      </body>
    </html>
  );
}
